import json
import os
import random

import spacy
from speakleash import Speakleash

try:
    from utils.functions import get_dir_path
except ImportError as e:
    print(f'Error: {e}')
    def get_dir_path(directory):
        return None

nlp = spacy.load("pl_core_news_md")

script_name = os.path.basename(__file__)
source_name = script_name.replace(".py", "")
source_url = "https://speakleash.org/"
source_description = "Instrukcje powstały dzięki ekstrakcji słów z polskiej wersji Wikipedii przetworzenia ich za pomocą pakietu Spacy oraz listy słów wulgarnych."

limit = 120000
words_limit = 1000

vulgar = [
    "chuj",
    "chuja",
    "chujek",
    "chuju",
    "chujem",
    "chujnia",
    "chujowy",
    "chujowa",
    "chujowe",
    "cipa",
    "cipę",
    "cipe",
    "cipą",
    "cipie",
    "dojebać",
    "dojebac",
    "dojebie",
    "dojebał",
    "dojebal",
    "dojebała",
    "dojebala",
    "dojebałem",
    "dojebalem",
    "dojebałam",
    "dojebalam",
    "dojebię",
    "dojebie",
    "dopieprzać",
    "dopieprzac",
    "dopierdalać",
    "dopierdalac",
    "dopierdala",
    "dopierdalał",
    "dopierdalal",
    "dopierdalała",
    "dopierdalala",
    "dopierdoli",
    "dopierdolił",
    "dopierdolil",
    "dopierdolę",
    "dopierdole",
    "dopierdoli",
    "dopierdalający",
    "dopierdalajacy",
    "dopierdolić",
    "dopierdolic",
    "dupa",
    "dupie",
    "dupą",
    "dupcia",
    "dupeczka",
    "dupy",
    "dupe",
    "huj",
    "hujek",
    "hujnia",
    "huja",
    "huje",
    "hujem",
    "huju",
    "jebać",
    "jebac",
    "jebał",
    "jebal",
    "jebie",
    "jebią",
    "jebia",
    "jebak",
    "jebaka",
    "jebal",
    "jebał",
    "jebany",
    "jebane",
    "jebanka",
    "jebanko",
    "jebankiem",
    "jebanymi",
    "jebana",
    "jebanym",
    "jebanej",
    "jebaną",
    "jebana",
    "jebani",
    "jebanych",
    "jebanymi",
    "jebcie",
    "jebiący",
    "jebiacy",
    "jebiąca",
    "jebiaca",
    "jebiącego",
    "jebiacego",
    "jebiącej",
    "jebiacej",
    "jebia",
    "jebią",
    "jebie",
    "jebię",
    "jebliwy",
    "jebnąć",
    "jebnac",
    "jebnąc",
    "jebnać",
    "jebnął",
    "jebnal",
    "jebną",
    "jebna",
    "jebnęła",
    "jebnela",
    "jebnie",
    "jebnij",
    "jebut",
    "koorwa",
    "kórwa",
    "kurestwo",
    "kurew",
    "kurewski",
    "kurewska",
    "kurewskiej",
    "kurewską",
    "kurewska",
    "kurewsko",
    "kurewstwo",
    "kurwa",
    "kurwaa",
    "kurwami",
    "kurwą",
    "kurwe",
    "kurwę",
    "kurwie",
    "kurwiska",
    "kurwo",
    "kurwy",
    "kurwach",
    "kurwami",
    "kurewski",
    "kurwiarz",
    "kurwiący",
    "kurwica",
    "kurwić",
    "kurwic",
    "kurwidołek",
    "kurwik",
    "kurwiki",
    "kurwiszcze",
    "kurwiszon",
    "kurwiszona",
    "kurwiszonem",
    "kurwiszony",
    "kutas",
    "kutasa",
    "kutasie",
    "kutasem",
    "kutasy",
    "kutasów",
    "kutasow",
    "kutasach",
    "kutasami",
    "matkojebca",
    "matkojebcy",
    "matkojebcą",
    "matkojebca",
    "matkojebcami",
    "matkojebcach",
    "nabarłożyć",
    "najebać",
    "najebac",
    "najebał",
    "najebal",
    "najebała",
    "najebala",
    "najebane",
    "najebany",
    "najebaną",
    "najebana",
    "najebie",
    "najebią",
    "najebia",
    "naopierdalać",
    "naopierdalac",
    "naopierdalał",
    "naopierdalal",
    "naopierdalała",
    "naopierdalala",
    "naopierdalała",
    "napierdalać",
    "napierdalac",
    "napierdalający",
    "napierdalajacy",
    "napierdolić",
    "napierdolic",
    "nawpierdalać",
    "nawpierdalac",
    "nawpierdalał",
    "nawpierdalal",
    "nawpierdalała",
    "nawpierdalala",
    "obsrywać",
    "obsrywac",
    "obsrywający",
    "obsrywajacy",
    "odpieprzać",
    "odpieprzac",
    "odpieprzy",
    "odpieprzył",
    "odpieprzyl",
    "odpieprzyła",
    "odpieprzyla",
    "odpierdalać",
    "odpierdalac",
    "odpierdol",
    "odpierdolił",
    "odpierdolil",
    "odpierdoliła",
    "odpierdolila",
    "odpierdoli",
    "odpierdalający",
    "odpierdalajacy",
    "odpierdalająca",
    "odpierdalajaca",
    "odpierdolić",
    "odpierdolic",
    "odpierdoli",
    "odpierdolił",
    "opieprzający",
    "opierdalać",
    "opierdalac",
    "opierdala",
    "opierdalający",
    "opierdalajacy",
    "opierdol",
    "opierdolić",
    "opierdolic",
    "opierdoli",
    "opierdolą",
    "opierdola",
    "piczka",
    "pieprznięty",
    "pieprzniety",
    "pieprzony",
    "pierdel",
    "pierdlu",
    "pierdolą",
    "pierdola",
    "pierdolący",
    "pierdolacy",
    "pierdoląca",
    "pierdolaca",
    "pierdol",
    "pierdole",
    "pierdolenie",
    "pierdoleniem",
    "pierdoleniu",
    "pierdolę",
    "pierdolec",
    "pierdola",
    "pierdolą",
    "pierdolić",
    "pierdolicie",
    "pierdolic",
    "pierdolił",
    "pierdolil",
    "pierdoliła",
    "pierdolila",
    "pierdoli",
    "pierdolnięty",
    "pierdolniety",
    "pierdolisz",
    "pierdolnąć",
    "pierdolnac",
    "pierdolnął",
    "pierdolnal",
    "pierdolnęła",
    "pierdolnela",
    "pierdolnie",
    "pierdolnięty",
    "pierdolnij",
    "pierdolnik",
    "pierdolona",
    "pierdolone",
    "pierdolony",
    "pierdołki",
    "pierdzący",
    "pierdzieć",
    "pierdziec",
    "pizda",
    "pizdą",
    "pizde",
    "pizdę",
    "piździe",
    "pizdzie",
    "pizdnąć",
    "pizdnac",
    "pizdu",
    "podpierdalać",
    "podpierdalac",
    "podpierdala",
    "podpierdalający",
    "podpierdalajacy",
    "podpierdolić",
    "podpierdolic",
    "podpierdoli",
    "pojeb",
    "pojeba",
    "pojebami",
    "pojebani",
    "pojebanego",
    "pojebanemu",
    "pojebani",
    "pojebany",
    "pojebanych",
    "pojebanym",
    "pojebanymi",
    "pojebem",
    "pojebać",
    "pojebac",
    "pojebalo",
    "popierdala",
    "popierdalac",
    "popierdalać",
    "popierdolić",
    "popierdolic",
    "popierdoli",
    "popierdolonego",
    "popierdolonemu",
    "popierdolonym",
    "popierdolone",
    "popierdoleni",
    "popierdolony",
    "porozpierdalać",
    "porozpierdala",
    "porozpierdalac",
    "poruchac",
    "poruchać",
    "przejebać",
    "przejebane",
    "przejebac",
    "przyjebali",
    "przepierdalać",
    "przepierdalac",
    "przepierdala",
    "przepierdalający",
    "przepierdalajacy",
    "przepierdalająca",
    "przepierdalajaca",
    "przepierdolić",
    "przepierdolic",
    "przyjebać",
    "przyjebac",
    "przyjebie",
    "przyjebała",
    "przyjebala",
    "przyjebał",
    "przyjebal",
    "przypieprzać",
    "przypieprzac",
    "przypieprzający",
    "przypieprzajacy",
    "przypieprzająca",
    "przypieprzajaca",
    "przypierdalać",
    "przypierdalac",
    "przypierdala",
    "przypierdoli",
    "przypierdalający",
    "przypierdalajacy",
    "przypierdolić",
    "przypierdolic",
    "qrwa",
    "rozjebać",
    "rozjebac",
    "rozjebie",
    "rozjebała",
    "rozjebią",
    "rozpierdalać",
    "rozpierdalac",
    "rozpierdala",
    "rozpierdolić",
    "rozpierdolic",
    "rozpierdole",
    "rozpierdoli",
    "rozpierducha",
    "skurwić",
    "skurwiel",
    "skurwiela",
    "skurwielem",
    "skurwielu",
    "skurwysyn",
    "skurwysynów",
    "skurwysynow",
    "skurwysyna",
    "skurwysynem",
    "skurwysynu",
    "skurwysyny",
    "skurwysyński",
    "skurwysynski",
    "skurwysyństwo",
    "skurwysynstwo",
    "spieprzać",
    "spieprzac",
    "spieprza",
    "spieprzaj",
    "spieprzajcie",
    "spieprzają",
    "spieprzaja",
    "spieprzający",
    "spieprzajacy",
    "spieprzająca",
    "spieprzajaca",
    "spierdalać",
    "spierdalac",
    "spierdala",
    "spierdalał",
    "spierdalała",
    "spierdalal",
    "spierdalalcie",
    "spierdalala",
    "spierdalający",
    "spierdalajacy",
    "spierdolić",
    "spierdolic",
    "spierdoli",
    "spierdoliła",
    "spierdoliło",
    "spierdolą",
    "spierdola",
    "srać",
    "srac",
    "srający",
    "srajacy",
    "srając",
    "srajac",
    "sraj",
    "sukinsyn",
    "sukinsyny",
    "sukinsynom",
    "sukinsynowi",
    "sukinsynów",
    "sukinsynow",
    "śmierdziel",
    "udupić",
    "ujebać",
    "ujebac",
    "ujebał",
    "ujebal",
    "ujebana",
    "ujebany",
    "ujebie",
    "ujebała",
    "ujebala",
    "upierdalać",
    "upierdalac",
    "upierdala",
    "upierdoli",
    "upierdolić",
    "upierdolic",
    "upierdoli",
    "upierdolą",
    "upierdola",
    "upierdoleni",
    "wjebać",
    "wjebac",
    "wjebie",
    "wjebią",
    "wjebia",
    "wjebiemy",
    "wjebiecie",
    "wkurwiać",
    "wkurwiac",
    "wkurwi",
    "wkurwia",
    "wkurwiał",
    "wkurwial",
    "wkurwiający",
    "wkurwiajacy",
    "wkurwiająca",
    "wkurwiajaca",
    "wkurwić",
    "wkurwic",
    "wkurwi",
    "wkurwiacie",
    "wkurwiają",
    "wkurwiali",
    "wkurwią",
    "wkurwia",
    "wkurwimy",
    "wkurwicie",
    "wkurwiacie",
    "wkurwić",
    "wkurwic",
    "wkurwia",
    "wpierdalać",
    "wpierdalac",
    "wpierdalający",
    "wpierdalajacy",
    "wpierdol",
    "wpierdolić",
    "wpierdolic",
    "wpizdu",
    "wyjebać",
    "wyjebac",
    "wyjebali",
    "wyjebał",
    "wyjebac",
    "wyjebała",
    "wyjebały",
    "wyjebie",
    "wyjebią",
    "wyjebia",
    "wyjebiesz",
    "wyjebie",
    "wyjebiecie",
    "wyjebiemy",
    "wypieprzać",
    "wypieprzac",
    "wypieprza",
    "wypieprzał",
    "wypieprzal",
    "wypieprzała",
    "wypieprzala",
    "wypieprzy",
    "wypieprzyła",
    "wypieprzyla",
    "wypieprzył",
    "wypieprzyl",
    "wypierdal",
    "wypierdalać",
    "wypierdalac",
    "wypierdala",
    "wypierdalaj",
    "wypierdalał",
    "wypierdalal",
    "wypierdalała",
    "wypierdalala",
    "wypierdalać",
    "wypierdolić",
    "wypierdolic",
    "wypierdoli",
    "wypierdolimy",
    "wypierdolicie",
    "wypierdolą",
    "wypierdola",
    "wypierdolili",
    "wypierdolił",
    "wypierdolil",
    "wypierdoliła",
    "wypierdolila",
    "zajebać",
    "zajebac",
    "zajebie",
    "zajebią",
    "zajebia",
    "zajebiał",
    "zajebial",
    "zajebała",
    "zajebiala",
    "zajebali",
    "zajebana",
    "zajebani",
    "zajebane",
    "zajebany",
    "zajebanych",
    "zajebanym",
    "zajebanymi",
    "zajebiste",
    "zajebisty",
    "zajebistych",
    "zajebista",
    "zajebistym",
    "zajebistymi",
    "zajebiście",
    "zajebiscie",
    "zapieprzyć",
    "zapieprzyc",
    "zapieprzy",
    "zapieprzył",
    "zapieprzyl",
    "zapieprzyła",
    "zapieprzyla",
    "zapieprzą",
    "zapieprza",
    "zapieprzy",
    "zapieprzymy",
    "zapieprzycie",
    "zapieprzysz",
    "zapierdala",
    "zapierdalać",
    "zapierdalac",
    "zapierdalaja",
    "zapierdalał",
    "zapierdalaj",
    "zapierdalajcie",
    "zapierdalała",
    "zapierdalala",
    "zapierdalali",
    "zapierdalający",
    "zapierdalajacy",
    "zapierdolić",
    "zapierdolic",
    "zapierdoli",
    "zapierdolił",
    "zapierdolil",
    "zapierdoliła",
    "zapierdolila",
    "zapierdolą",
    "zapierdola",
    "zapierniczać",
    "zapierniczający",
    "zasrać",
    "zasranym",
    "zasrywać",
    "zasrywający",
    "zesrywać",
    "zesrywający",
    "zjebać",
    "zjebac",
    "zjebał",
    "zjebal",
    "zjebała",
    "zjebala",
    "zjebana",
    "zjebią",
    "zjebali",
    "zjeby",
]

base_dir = os.path.dirname(os.path.abspath(__file__))
data_dir = get_dir_path("data") if not None else os.path.join(base_dir, "data")
output_dir = get_dir_path("output") if not None else os.path.join(base_dir, "output")
replicate_to = os.path.join(base_dir, "datasets")

sl = Speakleash(replicate_to)
counter = 0
wiki = sl.get("plwiki").data
instructions = []
words = {}

counter = 0

for txt in wiki:
    doc = nlp(txt)
    counter += 1
    print("Analiza słów, krok " + str(counter) + " z " + str(words_limit))
    for token in doc:
        if not token.is_stop and not token.is_punct and not token.is_digit and token.is_oov == False:
            word = token.text.strip()
            lemma = token.lemma_.strip()
            
            if not lemma or lemma[0].isupper():
                continue

            if token.pos_ == "VERB":
                if lemma not in words:
                    words[lemma] = word.lower()

            if token.pos_ == "NOUN":
                if lemma not in words:
                    words[lemma] = word.lower()

            if token.pos_ == "ADJ":
                if lemma not in words:
                    words[lemma] = word.lower()

    if counter > words_limit:
        break


print(words)

vulgar_word_counter = len(vulgar)
normal_word_counter = 5 * vulgar_word_counter

if normal_word_counter > len(words):
    normal_word_counter = len(words)

instructions_template = [
    "Czy podane słowo jest niecenzuralne?",
    "Czy podane słowo jest wulgarne?",
    "Czy podane słowo jest przekleństwem?",
    "Czy podane słowo jest obraźliwe?",
    "Czy podane słowo jest nieodpowiednie?",
    "Czy podane słowo jest wulgarnym wyrażeniem?",
    "Czy podane słowo jest nieprzyzwoite?",
]

for v in vulgar:

    instruction = random.choice(instructions_template)
    input = v
    output = random.choice(["Tak", "tak",f"Słowo: {v} jest wulgaryzmem", f"Słowo: {v} jest wulgarne", f"Słowo: {v} jest przekleństwem", f"Słowo: {v} jest obraźliwe", f"Słowo: {v} jest nieodpowiednie", f"Słowo: {v} jest niestosowne", f"Słowo: {v} jest wulgarnym wyrażeniem", f"Słowo: {v} jest nieprzyzwoite"])

    instructions.append(
        {
            "instruct": instruction,
            "input": input,
            "output": output,
            "source_name": source_name,
            "source_url": source_url,
            "source_description": source_description,
            "script_name": script_name,
        }
    )


counter = 0
for k in words.keys():
    counter += 1
    if counter > normal_word_counter:
        break

    instruction = random.choice(instructions_template)
    input = words[k]
    output = random.choice(["Nie", "nie",f"Słowo: {words[k]} nie jest wulgaryzmem", f"Słowo: {words[k]} nie jest wulgarne", f"Słowo: {words[k]} nie jest przekleństwem", f"Słowo: {words[k]} nie jest obraźliwe", f"Słowo: {words[k]} nie jest nieodpowiednie", f"Słowo: {words[k]} nie jest niestosowne", f"Słowo: {words[k]} nie jest wulgarnym wyrażeniem", f"Słowo: {words[k]} nie jest nieprzyzwoite"])

    instructions.append(
        {
            "instruct": instruction,
            "input": input,
            "output": output,
            "source_name": source_name,
            "source_url": source_url,
            "source_description": source_description,
            "script_name": script_name,
        }
    )


random.shuffle(instructions)
with open(
    os.path.join(output_dir, script_name.replace(".py", ".json")), "w", encoding="utf-8"
) as f:
    json.dump(instructions, f, indent=4, ensure_ascii=False)
print("Instructions: " + str(len(instructions)))
